# ConfigMap for custom index.html
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: my-demo
data:
  index.html: |
    <!doctype html>
    <html>
    <head><meta charset="utf-8"><title>NGINX on Kubernetes</title></head>
    <body style="font-family: sans-serif">
    <h1>✅ It works !</h1>
    <p>Served by NGINX Deployment on K8s (NodePort).</p>
    </body>
    </html>

---
# Deployment for NGINX
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: my-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-index
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: nginx-index
        configMap:
          name: nginx-index

---
# Service to expose NGINX
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: my-demo
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30055