# ConfigMap for custom index.html
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: my-demo
data:
  index.html: |
    <!doctype html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <title>NGINX on Kubernetes</title>
      <style>
        body {
          margin: 0;
          padding: 0;
          height: 100vh;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          background: linear-gradient(-45deg, #ff416c, #ff4b2b, #1e3c72, #2a5298);
          background-size: 400% 400%;
          animation: gradientBG 12s ease infinite;
          color: white;
          text-align: center;
        }

        @keyframes gradientBG {
          0% {background-position: 0% 50%;}
          50% {background-position: 100% 50%;}
          100% {background-position: 0% 50%;}
        }

        h1 {
          font-size: 80px;
          margin: 20px 0;
          text-shadow: 2px 2px 10px rgba(0,0,0,0.5);
        }

        h2 {
          font-size: 40px;
          margin-bottom: 30px;
          color: #ffe97f;
        }

        p {
          font-size: 26px;
          background: rgba(0,0,0,0.4);
          padding: 10px 20px;
          border-radius: 10px;
          display: inline-block;
        }

        .footer {
          margin-top: 80px;
          font-size: 18px;
          color: #ddd;
        }
      </style>
    </head>
    <body>
      <h1>✅ It Works!</h1>
      <h2>🔥 Served by Kubernetes Deployment<br>(NodePort Service)</h2>
      <p>🚀 Automated CI/CD with <b>ArgoCD</b></p>
      <div class="footer">
        © 2025 | Deployed via GitOps | Made with ❤️ on Kubernetes
      </div>
    </body>
    </html>:

---
# Deployment for NGINX
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: my-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-index
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: nginx-index
        configMap:
          name: nginx-index

---
# Service to expose NGINX
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: my-demo
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30055